categories:
  - title: '🚀 Features'
    label: 'feat'
  - title: '🐛 Bug Fixes'
    label: 'fix'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: '📃 Documentation'
    label: 'docs'
  - title: '🔧 Testing'
    label: 'test'
autolabeler:
  - label: 'feat'
    title: 
    - 'feat:'
  - label: 'fix'
    title: 
    - 'fix:'
  - label: 'chore'
    title: 
    - 'chore:'
  - label: 'docs'
    title: 
    - 'docs:'
  - label: 'test'
    title: 
    - 'test:'
template: |
  ## v$RESOLVED_VERSION

  $CHANGES
