# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    outputs:
      releaseId: ${{ steps.releaseDrafter.outputs.id }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - run: yarn

    - id: releaseDrafter
      uses: release-drafter/release-drafter@v5
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Publish a Release
      uses: StuYarrow/publish-release@v1
      with:
        id: ${{ needs.build.releaseDrafter.outputs.id }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

